config/routes.rb
BasicAdmin::Application.routes.draw do

  devise_for :users

  namespace :admin do
      get "/" => "home#index"
      resources :users
  end

  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.is_admin?
      can :manage, :all
    end

  end
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  included do
    # Allow filters to be applied to seach criteria
    def self.filter(params = nil, order_by = nil, defaults = {})
      params = [] unless params
      order_by = order_by || "id"
      search_params = params[:search] || defaults
      sort = params[:sort].blank? ? order_by : params[:sort]
      direction = params[:direction] || "asc"
      direction = %w[asc desc].include?(direction) ? direction : "asc"
      page = params[:page] || "1"

      things = scoped
      search_params.each do |pk, pv|
        if pv.is_a?(Hash)
          pv.each do |pvk, pvv|
            if pvk == "exact"
              things = things.where("#{table_name}.#{pk} = ?", pvv) unless pvv.blank?
            elsif pvk == "date_after"
              things = things.where("#{table_name}.#{pk} >= ?", pvv) unless pvv.blank?
            elsif pvk == "date_before"
              things = things.where("#{table_name}.#{pk} <= ?", pvv) unless pvv.blank?
            end
          end
        else
          if pv.is_a?(String)
            things = things.where("#{table_name}.#{pk} ILIKE ?", "%#{pv}%") unless pv.blank?
          else
            things = things.where("#{table_name}.#{pk} = ?", pv) unless pv.blank?
          end
        end
      end

      sort = "lower(#{sort})" if things.columns_hash[sort] and things.columns_hash[sort].type == :string
      things.order( sort + ' ' + direction).paginate(:per_page => Setting.per_page, :page => page)
    end
  end
end

app/models/setting.rb
class Setting < RailsSettings::CachedSettings
end

app/models/user.rb
class User < ActiveRecord::Base

  # !**************************************************
  # !                Associations
  # !**************************************************

  # !**************************************************
  # !                Validations
  # !**************************************************
  validates_presence_of :name

  # !**************************************************
  # !                Callbacks
  # !**************************************************

  # !**************************************************
  # !                  Other
  # !**************************************************
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  include Filterable

  def is_admin?
    self.admin
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  def index

  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  load_and_authorize_resource

  def index
    @users = User.filter(params)

    @columns = ["name", "email"]
    @filters = { "name" => nil, "email" => nil }

    respond_to do |format|
        format.html
        format.js
    end
  end

  def show
  end

  def new
  end

  def create
    @user = User.new(user_params)
    @user.password = Devise.friendly_token.first(20) if @user.password.blank?

    if @user.save
      redirect_to admin_user_path(@user), notice: "User created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user), notice: "#{@user.name} updated"
    else
      render :edit
    end
  end

  def destroy
    redirect_to admin_users_path, alert: "You can't delete yourself" and return if current_user == @user
    if @user.delete
      flash[:notice] = "User #{@user.name} deleted"
      respond_to do |format|
        format.html { redirect_to admin_users_path }
        format.js
      end
    else
      redirect_to admin_user_path(@user), alert: "Could not delete user #{@user.name}"
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :admin)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  layout 'admin'

  before_filter :check_admin

  private

    def check_admin
      redirect_to :root unless current_user.is_admin?
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!, :fix_cancan
  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  # Throw away flash messages after AJAX request
  # (stops alerts etc popping up on next page load)
  after_filter { flash.discard if request.xhr? }

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
    end

    # Needed to make strong parameters work in create methods with CanCan
    def fix_cancan
      resource = controller_name.singularize.to_sym
      method = "#{resource}_params"
      params[resource] &&= send(method) if respond_to?(method, true)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!

  def index
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def sortable_filters(columns, filters)
    render partial: 'includes/sortable_filters', locals: {columns: columns, filters: filters}
	end

	def filter_default(k, v, defaults = {})
	  if v and v[:input_type] == :settings_select
    	defaults.dig(k) ? defaults.dig(k, "exact") : ''
    elsif v and v[:input_type] == :relation_select
      defaults.dig(k) ? defaults.dig(k).id : ''
    elsif v and v[:input_type] == :date_before
      defaults.dig(v[:field].to_s, "date_before") ? l(defaults.dig(v[:field].to_s, "date_before"), format: :short_date) : ''
    elsif v and v[:input_type] == :date_after
      defaults.dig(v[:field].to_s, "date_after") ? l(defaults.dig(v[:field].to_s, "date_after"), format: :short_date) : ''
    else
      defaults[k]
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/will_paginate_helper.rb
module WillPaginateHelper
  class AjaxRenderer < WillPaginate::ActionView::LinkRenderer
    private
      def link(text, target, attributes = {})
        if target.is_a? Fixnum
          attributes[:rel] = rel_value(target)
					attributes["data-page"] = target
          target = url(target)
        end
        attributes[:href] = target
        tag(:a, text, attributes)
      end
  end
end

app/views/admin/home/index.html.erb
<h1>Site Admin</h1>
<div class="row">
  <div class="col-md-4">
    <%= render partial: 'admin/users/panel_recent' %>
  </div>
  <div class="col-md-4">

    <div class="panel panel-warning">
      <div class="panel-heading">Some Other Panel</div>
      <div class="panel-body">
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tincidunt luctus quam, sed fermentum magna porttitor in. Quisque luctus magna eget est congue sit amet aliquet nisl fermentum. Cras non libero est, nec volutpat lacus. Nullam vel dolor est. Sed vel ligula et mi dapibus gravida nec in risus. Sed nunc dui, lacinia non consectetur ac, pharetra a lacus. Nunc a dictum felis.</p>
      </div>
      <div class="panel-footer">Wee lorem footer</div>
    </div>

  </div>
</div>

app/views/admin/users/_form.html.erb
<%= simple_form_for user, url: admin_user_path(user), role: "form", html: {class: "form-horizontal"} do |f| %>

    <%= f.input :name, class: "form-control", placeholder: "Bob Smith", :autofocus => true, input_html: { class: "form-control"} %>
    <%= f.input :email, class: "form-control", placeholder: "example@example.com", input_html: { class: "form-control"} %>
    <%= f.input :admin, input_html: { class: "form-control"} unless current_user == user %>

    <%= link_to "Cancel", admin_users_path, class: "btn btn-default" %>
    <%= f.submit user.new_record? ? "Add User" : "Save User", class: "btn btn-primary", disable_with: "Saving" %>
<% end %>

app/views/admin/users/_panel_recent.html.erb
<div class="panel panel-info">
  <div class="panel-heading">Recently Created Users</div>
  <div class="list-group">
    <% User.order("created_at DESC").limit(5).each do |u| %>
      <a href="<%= admin_user_path(u) %>" class="list-group-item">
        <%= u.name %> <span class="pull-right"><%= l(u.created_at, format: :good) %></span>
      </a>
    <% end %>
  </div>
  <div class="panel-footer"><%= link_to "See all #{pluralize(User.count, "user")}", admin_users_path %></div>
</div>

app/views/admin/users/_user.html.erb
<tr id="user-<%= user.id %>">
  <td><%= link_to user.name, admin_user_path(user) %></td>
  <td><%= user.email %></td>
  <td>
    <%= link_to "Edit", edit_admin_user_path(user), class: "btn btn-primary" %>
    <%= link_to "Delete", admin_user_path(user), method: :delete, remote: true, class: "btn btn-danger", data: {confirm: "Are you sure you want to delete #{user.name}?"} unless current_user == user  %>
  </td>
</tr>

app/views/admin/users/destroy.js.erb
show_notice("<%= flash[:notice] %>");
$("#user-<%= @user.id %>").addClass("danger").fadeOut(1000);

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<h1>
  Users
  <%= link_to "Add a New User", new_admin_user_path, class: "btn btn-primary pull-right" %>
</h1>

<%= render partial: 'includes/sortable_table', locals: {items: @users} %>

app/views/admin/users/index.js.erb
<%= render partial: "includes/filter_index", locals: {items: @users} %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render partial: "form", locals: {user: @user} %>

app/views/admin/users/show.html.erb
<h1>
  Details for <%= @user.name %>
  <% if @user == current_user %>
    <small>(That's you!)</small>
  <% end %>
</h1>

<dl>
  <dt>Name</dt>
  <dd><%= @user.name %></dd>

  <dt>Email</dt>
  <dd><%= @user.email %></dd>

  <dt>Admin User?</dt>
  <dd><%= @user.is_admin? ? "Yes" : "No" %></dd>
</dl>

<div>
<%= link_to "Back", admin_users_path, class: "btn btn-default" %>
<%= link_to "Edit", edit_admin_user_path(@user), class: "btn btn-primary" %>
<%= link_to "Delete", admin_user_path(@user), class: "btn btn-danger", method: :delete, confirm: "Are you sure you want to delete #{@user.name}?" unless @user == current_user %>
</div>

app/views/home/index.html.erb
<div class="container theme-showcase">
  <h1>My Awesome Site</h1>
</div> <!-- /container -->

app/views/includes/_filter_bar.html.erb
<div class="well">
  <%= form_tag request.path, method: :get, remote: true, class: 'filter-form form-inline', role: "form" do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <% defaults = @filters[:defaults] || {} %>
    <% filters = @filters[:options] || @filters %>

    <div class="form-group info">Search:</div>

    <% filters.each do |fk,fv| %>
      <% if fk.nil? %>

      <% elsif fv %>
        <% field_name = fv[:field] || fk %>

        <% if fv[:input_type] == :settings_select %>
          <% setting = fv[:setting] || fk %>
          <div class="form-group">
          <%= select_tag( "search[#{field_name}][exact]",
                          options_for_select( select_translations(setting), filter_default(fk, fv, defaults) ),
                          prompt: field_name,
                          class: "form-control") %>
          </div>

        <% elsif fv[:input_type] == :relation_select %>
          <% name_method = fv[:name_method] || :name %>
          <div class="form-group">
            <%= select_tag( "search[#{field_name}][exact]",
                            options_from_collection_for_select(fv[:options], :id, name_method, filter_default(fk, fv, defaults) ),
                            prompt: field_name,
                            class: "form-control") %>
          </div>
        <% elsif fv[:input_type] == :date_after %>
          <div class="form-group">
            <%= text_field_tag  "search[#{field_name}][date_after]",
                                filter_default(fk, fv, defaults),
                                placeholder:fk,
                                type: :date,
                                class: "form-control" %>
          </div>
        <% elsif fv[:input_type] == :date_before %>
          <div class="form-group">
            <%= text_field_tag  "search[#{field_name}][date_before]",
                                filter_default(fk, fv, defaults),
                                placeholder: fk,
                                type: :date,
                                class: "form-control" %>
          </div>
        <% elsif fv[:input_type] == :exact %>
          <div class="form-group">
            <%= text_field_tag  "search[#{field_name}][exact]",
                                filter_default(fk, fv, defaults),
                                placeholder: fk,
                                class: "form-control" %>
          </div>
        <% else %>
          <div class="form-group">
            <%= text_field_tag "search[#{fk}]", filter_default(fv), placeholder: fk, class: "form-control" %>
          </div>
        <% end %>
      <% else %>
        <div class="form-group">
          <%= text_field_tag "search[#{fk}]", filter_default(fk, fv, defaults), placeholder: fk, class: "form-control" %>
        </div>
      <% end %>
    <% end %>

    <div class="form-group">
      <%= link_to "<span class=\"glyphicon glyphicon-remove-circle\"></span> Reset Search".html_safe,
                  request.path,
                  remote: true,
                  class: "reset-filters" %>
    </div>
  <% end %>
</div>

app/views/includes/_filter_index.js.erb
<% # We only want to reset the form on submit, otherwise the current field loses focus %>
<% if params[:search].nil? %>
  $("#filter-bar").html("<%= j render partial: 'includes/filter_bar' %>");
<% end %>
$("table#filter-list thead").html("<%= j render partial: 'includes/sortable_head' %>");
$("table#filter-list tbody").html("<%= j render(items) || "<tr><td colspan=\"#{@columns.count+1}\">#{t("no_matches")}</td></tr>".html_safe %>");
$(".js-pagination").html("<%= j will_paginate items, renderer: BootstrapPagination::Rails %>");

form_overrides();

app/views/includes/_info_message.html.erb
<div id="info-message">
  <div class="alert alert-success" id="info-notice"><%= notice %></div>
  <div class="alert alert-danger" id="info-alert"><%= alert %></div>
</div>

<script>

function show_alerts()
{
  $("#info-message").fadeIn().delay(3000).fadeOut();
}

function show_notice(content) {
  $("#info-notice").html(content);
  $("#info-notice").show();
  show_alerts();
}

function show_alert(content) {
  $("#info-alert").html(content);
  $("#info-alert").show();
  show_alerts();
}

$(document).ready(function(){
  $("#info-message").hide();
  $("#info-notice").hide();
  $("#info-alert").hide();
  <%= 'show_alert();' if flash[:alert] %>
  <%= 'show_notice();' if flash[:notice] %>

});
</script>

app/views/includes/_sortable_head.html.erb
<tr>
  <% @columns.each do |c| %>
    <% css_class = (c == params[:sort]) ? "current #{params[:direction]}" : nil %>
    <% direction = (c == params[:sort] && params[:direction] == "asc") ? "desc" : "asc" %>
    <th>
      <%= link_to c.humanize, params.merge(:sort => c, :direction => direction, :page => nil), {class: css_class, remote: true} %>
      <% if c == params[:sort] %><span class="caret <%= direction %>"></span><% end %>
    </th>
  <% end %>
  <th class='actions'>&nbsp;</th>
</tr>

app/views/includes/_sortable_table.html.erb
<div class="filter-bar" id="filter-bar">
  <%= render partial: 'includes/filter_bar' %>
</div>

<div class="table-responsive">
  <table id="filter-list" class="table table-striped table-hover">
    <thead>
      <%= render partial: 'includes/sortable_head' %>
    </thead>
    <tbody>
      <%= render(items) || "<tr><td colspan=\"#{@columns.count+1}\">#{t("no_matches")}</td></tr>".html_safe %>
    </tbody>
  </table>

  <div class="js-pagination">
    <%= will_paginate items, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicAdmin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Admin", admin_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Users", admin_users_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-align-justify"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Account", edit_user_registration_path %></li>
                <li><%= link_to "Go to Site", :root %>
                <li class="divider"></li>
                <li><%= link_to "Sign Out",
                                destroy_user_session_path,
                                :method => :delete %>
                </li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <%= render partial: 'includes/info_message' %>
      <%= yield %>
    </div><!-- /.container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicAdmin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "My Site", :root, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-align-justify"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Account", edit_user_registration_path %></li>
                  <% if current_user.is_admin? %>
                    <li><%= link_to "Admin", admin_path if current_user.is_admin? %></li>
                  <% end %>
                  <li class="divider"></li>
                  <li><%= link_to "Sign Out",
                                  destroy_user_session_path,
                                  :method => :delete %>
                  </li>

                </ul>
              </li>
            <% else %>
              <li><%= link_to('Sign In', new_user_session_path)  %></li>
            <% end %>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <%= render partial: 'includes/info_message' %>
      <%= yield %>
    </div><!-- /.container -->

  </body>
</html>